version: "3.8"

volumes:
  arclab-postgres:
  # production
  # ghost-data:

services:
  postgres:
    image: "postgres:alpine"
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - "arclab-postgres:/var/lib/postgresql/data"

  blog:
    restart: always

    build:
      context: "../blog.arcbjorn.com"
      dockerfile: "../blog.arcbjorn.com/Dockerfile.static"
      target: development
    ports:
      # - "5173:3000" # for adapter-node
      - "5173:80" # for adapter-static

  ghost:
    restart: always

    image: ghost:5
    ports:
      - 8080:2368
    # environment:
    #   url: http://localhost:2368
    volumes:
      # production
      # - ghost-data:/var/lib/ghost/content
      - ./content:/var/lib/ghost/content
