edgedb:
  image: edgedb/edgedb
  environment:
    - EDGEDB_SERVER_SECURITY=insecure_dev_mode
    - EDGEDB_SERVER_DATABASE=edgedb
    - EDGEDB_SERVER_PASSWORD=edgedb
  volumes:
    - ./dbschema:/dbschema
    - ./credentials:/root/.config/edgedb/credentials
    - edgedb_data:/var/lib/edgedb/data
  ports:
    - "5656:5656"

volumes:
  edgedb_data:
