version: "3.8"

# volumes:
#   arclab-postgres:
#   ghost-data:

services:
  postgres:
    image: "postgres:alpine"
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - "arclab-postgres:/var/lib/postgresql/data"

  blog:
    build:
      context: "../blog.arcbjorn.com"
      target: development
    ports:
      - "3000:3000"
